name: confidential_chat_app
version: 1.0.0+1
publish_to: none
description: A Confidential Chat Flutter project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.3.1
  flutter_spinkit: ^5.1.0
  awesome_dialog: ^3.0.2
  google_fonts: ^4.0.3
  bouncing_widget: ^2.0.0
  get: 4.6.5
  fluttertoast: ^8.1.2
  connectivity_plus: ^3.0.2
  flutter_svg: ^0.22.0
  shared_preferences: ^2.0.17
  intl: #^0.18.0


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
